require("user.options").setup()
require("user.keymaps").setup()
require("user.plugins").setup()
require("user.cmp").setup()
require("user.colorscheme").setup()
require("user.lualine").setup()
require("user.bufferline").setup()
require("user.lspconfig").setup()
require("user.nullls").setup()
require("user.telescope").setup()
require("user.treesitter").setup()
require("user.gitsigns").setup()
require("user.neotree").setup()
-- require("user.codeium").setup()
-- @require("user.copilot").setup()
require("colorizer").setup()
require("dressing").setup()
